### ISSUE TITLE
how to check number its use whatsapp or not 

### ISSUE THREAD

**Issue by vinayakvasu** [nian88/whatsapp-api#3]
how to check number its use whatsapp or not

**Comment by nian88** [comment]
You can use this code

await sock.onWhatsApp('62223612')

**Comment by nian88** [comment]
[check this app.js](https://github.com/nian88/whatsapp-api/blob/2301e6a0415555f23f9f385ab45d111d53ea6085/app.js#L89-L95)

`    const [result] = await sock.onWhatsApp(number)
    if(result === undefined){
        return res.status(200).json({
                status: true,
                response: "Your Number not Register on WhatsApp"
            });
    }
    `
